config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :comments, only: [:create, :destroy]
  end

  resources :meetings, only:[:create, :update]
  devise_for :users

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :meetings
  has_many :comments, dependent: :destroy
  
  acts_as_taggable # Alias for acts_as_taggable_on :tags

	def available?
		current_meeting.nil?
	end

	def current_meeting
		meetings.on_date.first
	end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
  validates :body, presence: true
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	validates_presence_of :user_id, :book_id, :start_datetime
  belongs_to :book
  belongs_to :user

  scope :on_date, -> { where(end_datetime: nil) }
  scope :off, -> { where.not(end_datetime: nil) }

  def on_date?
  	end_datetime.nil?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :meetings 
  has_many :books


  	def current_book
  		current_meeting.book
  	end

	def current_meeting
		meetings.on_date.first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :phone_number]
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :create, :new, :edit, :destroy]
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
        @meeting = current_user.meetings.build(book_id: @book.id)
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :user_id, :tag_list, :email)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_book
	before_action :set_comment, only: :destroy

  def create
  	@comment = @book.comments.new(comment_params)
  	@comment.save
  end

  def destroy
  	@comment.destroy
  end

  private

  def set_book
  	@book = Book.find(params[:book_id])
  end

  def set_comment
  	@comment = @book.comments.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(:body)
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
 	before_action :set_meeting, only: :update

  def create
  	@meeting = Meeting.new(meeting_params)
  	@meeting.start_datetime = Time.now

  	@meeting.save
  	redirect_to @meeting.book
  end

  def update
  	@meeting.update(meeting_params)
  	redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:book_id, :user_id, :end_datetime)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :tag_list %>
    <%= f.hidden_field :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? && current_user.current_meeting %>
  <div class="alert alert-info" role="alert">
    <%= current_user.current_book.id %>번 북과 데이트 중이에요^^ 
        <%= simple_form_for current_user.current_meeting do |f| %>
          <%= f.hidden_field :end_datetime, value: Time.now %>
          <%= f.submit "데이트 끝내기" %>
        <% end %>

    </div>
<% end %>

<h1>Listing Books</h1>



<table class="table table-striped">
  <thead>
    <tr>
      <th>NO.</th>
      <th>description</th>
      <th>상태</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
      <% @books.each do |book| %>    
      <tr>
        <td><%= book.id %></td>
        <td><%= book.tag_list %><small>( <%= book.comments.size %> )</small></td>
        <td>
          <% if book.available? %>
            데이트 가능
          <% else %>
            데이트 중
          <% end %>
        </td>
        <td><%= link_to 'Show', book %></td>
             

        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>NO.</strong>
  <%= @book.id %>
</p>

    <% if current_user.name == "허석영" or book.user_id == current_user.id %>
      <p><strong>책이름: </strong><%= @book.title %></p>  
    <% end %>

<p>
  <strong>주선자: </strong>
  <%= @book.user_id %>
</p>
      

<p>
  <strong>Description</strong>
  <%= @book.tag_list %>
</p>

<% current_meeting = @book.current_meeting %>

<p>
  <strong>상태: </strong>
	    <% if @book.available? %>
          데이트 가능
      <% else %>
          데이트 중 with <strong><%= current_meeting.user.name %></strong>
    
    	<% if current_user.name == "허석영" or book.user_id == current_user.id %>
          (<%= current_meeting.user.phone_number %>)</p>  
      <% end %>
        	<p>데이트 시작일: <%= current_meeting.start_datetime %></p>	
    			<p>데이트 마감일: <%= current_meeting.start_datetime + 21.days %></p>	
    	<% end %>
</p>

		<% if @book.available? && current_user.current_meeting.nil? %>
			<%= simple_form_for @meeting do |f| %>
				<%= f.hidden_field :user_id %>
				<%= f.hidden_field :book_id %>
				<%= f.submit "데이트 시작" %>
			<% end %>
		<% end %>

<%= render "comments/comments" %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Destroy', books_path, method: :delete, data: { confirm: 'Are you sure?'} %> |
<%= link_to 'Back', books_path %>

app/views/comments/_comment.html.erb
<li id="comment_<%=comment.id %>">
  <%= comment.body %>,
  <%= time_ago_in_words(comment.created_at) %> ago
  <%= link_to fa_icon("times-circle-o"), [comment.book, comment], method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
</li>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comment_header">
    <h2>Comments:</h2>
  </div>
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>
  <div class='comments_form'>
    <%= render "comments/form" %>
  </div>
</div>

app/views/comments/_form.html.erb
<% comment = @book.comments.new %>
<div id="comments_form_<%=@book.id%>">
<%= simple_form_for([@book, comment], remote: true ) do | f | %>
  <div class='form-inputs'>
    <%= f.input :body, label: false, placeholder: '반납 시 책에 대한 후기를 남겨주세요~',  input_html: { rows: 5 } %>
  </div>
  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@book.id%>">
<% if @book.comments.size > 0 %>
  <%= render @book.comments %>
<% else %>
  <li>
    No comments
  </li>
<% end %>
</ul>

app/views/comments/create.js.erb
<% if @comment.errors.size == 0 %>
  $('<%=j render @comment %>').appendTo($("#comments_list_<%=@book.id %>")).hide().fadeIn('fast');
  $("#comments_form_<%=@book.id %> form")[0].reset();
<% else %>
  alert("Please submit after commenting...");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Bdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
  	<%= link_to "Blind Book", root_path, class: "navbar-brand" %>
	</div>
		<ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-brand" %>
      <% else %>
			  <%= link_to "Log in", new_user_session_path, class: "navbar-brand" %>
      <% end %>
		</ul>
	</div>
</nav>

<div class ="container" >

<%= yield %>

</div>

</body>
</html>

app/views/meetings/create.html.erb
<h1>Meetings#create</h1>
<p>Find me in app/views/meetings/create.html.erb</p>

app/views/meetings/update.html.erb
<h1>Meetings#update</h1>
<p>Find me in app/views/meetings/update.html.erb</p>